services:
  - type: web
    name: di-vision-iso
    env: python
    plan: starter
    buildCommand: ./build.sh
    startCommand: python manage.py migrate && gunicorn safety_mvp.wsgi:application
    disk:
      name: di-vision-media
      mountPath: /opt/render/project/src/media
      sizeGB: 1
    envVars:
      - key: DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.11.5
