"""
Shared checklist step labels.
Imported by both views.py (form rendering) and pdf_export.py (PDF generation)
so the question text appears in both the UI and exported documents.
"""

CHECKLIST_STEP_MAP = {
    'Daily': [
        'Permit to Work (PTW) reviewed and signed for all high-risk activities.',
        'Hazard identification (HIRA) completed for the work area.',
        'Any near-miss or incident occurred / reported today?',
        'Toolbox talk conducted at shift start.',
        'Emergency equipment (fire extinguishers, first aid kit) inspected and serviceable.',
        'Visitor / contractor site induction completed where applicable.',
        'Area risk assessment reviewed and communicated to all team members.',
        'Shift handover safety briefing completed.',
        'Communication channels (radio / phone) confirmed operational.',
        'Environmental conditions (weather, visibility, ground) assessed and acceptable.',
        'Traffic management plan in place and communicated.',
        'Isolation / Lockout-Tagout (LOTO) procedures applied where required.',
        'Working-at-height equipment inspected and in service.',
        'Confined space entry permit in place where required.',
        'End-of-day site secured and equipment properly stored.',
    ],
    'Weekly': [
        'Management / supervisor safety walk conducted and documented.',
        'Legal and compliance register reviewed for any updates.',
        'CAPA actions reviewed and progress updated.',
        "Previous week's findings and action items closed out.",
        'Safe man-hours for the week logged and verified.',
        'Weekly toolbox talk topic selected, material prepared, and delivered.',
        'Training and competency records reviewed and updated.',
        'Incident and near-miss register reviewed and trend analysed.',
        'Contractor safety files reviewed and current.',
        'Emergency response drill scheduled or conducted.',
        'Equipment maintenance records checked and current.',
        'Environmental compliance checks completed.',
        'Safety notice board updated with current information.',
        'OHS objectives and KPI data collected and reviewed.',
        'High-risk activities for the following week identified and planned.',
    ],
    'Mobile Equipment': [
        'Body work and general condition.',
        '*Wheels (tyres/rims).',
        '*Windscreen and all windows.',
        '*Wipers.',
        '*License disc.',
        '*Rear view and side mirrors.',
        '*Headlights, tail lights, brake lights and indicators.',
        '*Number plates.',
        '*Amber flashing light (when prescribed).',
        '*Buggy whip holder (when prescribed).',
        'Reflective yellow/red strips.',
        '*Roll over bars (LDVs, when prescribed).',
        '*Radiator water.',
        '*Battery condition, connections and water.',
        '*Oil level.',
        '*Brake fluid level.',
        '*Lubricant leaks.',
        'Seats.',
        '*Instrument panel - all instruments working.',
        '*Steering wheel and test steering.',
        'Hooter.',
        '*Reverse hooter (when prescribed).',
        '*Rear view mirror.',
        '*Seat belts.',
        '*Handbrake.',
        '*Footbrake and test brakes.',
        'Spare wheel.',
        'Jack and wheel spanner.',
        '*Emergency triangles.',
        'First aid kit (if applicable).',
        '*Stop blocks (operational vehicles).',
        '*Fire extinguisher (operational vehicle).',
    ],
    'Lighting Tower': [
        'Yellow door Assy condition.',
        'Mudguard condition.',
        'Lifting Jack top wind condition.',
        'Lifting jack side wind drawbar condition.',
        'Mast Assy condition.',
        'Outlet panel condition.',
        'Wheel/Rim condition.',
        'Emergency stop bottom condition.',
        'Roof Assy condition.',
        'Radiator coolant level.',
        'Battery and terminals condition.',
        'Oil level.',
        'Lubricant leaks.',
        'Diesel level.',
        'Diesel tank condition.',
        'Control panel condition.',
        'Water pump condition.',
        'Oil dipstick condition.',
        'Hour meter condition.',
        'Fuel pump Assy condition.',
        'Start motor condition.',
        'Alternator belt condition.',
        'Fan Assy condition.',
        'LED condition.',
        'Led floodlight condition.',
        'Driver condition.',
        'Coil cord condition.',
        'Winch RBW Assy condition.',
        'Last Service.',
    ],
    'Drilling Machine Surface': [
        'Structure Condition',
        'Guide Rod Condition',
        'Main Which Pulley Condition',
        'Main Hosting Pulley Condition',
        'Wire Line Pulley Condition',
        'Support Leg Condition',
        'Main Cylinder Condition',
        'Slides Condition',
        'Light Condition',
        'Gauges Condition',
        'Levers Condition',
        'Emergency Stop Bottom Condition',
        'RCS (Rig Control System) Condition',
        'Bottom Light Condition',
        'Ignition Switch Condition',
        'Coolant Level',
        'Engine Oil Level',
        'Hydraulic Oil Level',
        'Fuel Level',
        'Leakages',
        'Batteries Condition',
        'Service Record',
        'Rod Clamp Condition',
        'Chuck Jaw Condition',
        'Platform Condition',
        'Fire Suppression Condition',
        'Fire Extinguisher Condition',
        'Beacon Condition',
        'Mud Mixer Condition',
        'Crawlers Condition',
        'Critical Grease Points',
        'Hydraulic Jacks Condition',
        'Main Hoist System Condition',
        'Wire-Line System Condition',
        'Rotation Unit Condition',
        'Gear Oil Level',
        'Hydraulic Oil Cooler Condition',
        'Relief Pressure Condition',
        'Water Pump R35 Condition',
        'Pipe Wrenches Condition',
        'Inner Tube Spanner Condition',
        'Head Assembly Condition',
        'Overshot Assembly Condition',
        'Water Swivel Condition',
        'Hosting Plug Condition',
        'Camera Survey Condition',
        'Orientation Tool Condition',
    ],
    'Environmental': [
        'Environmental permits and license conditions for this work area are current and available.',
        'Applicable environmental legal requirements have been identified for this task/activity.',
        'Environmental aspects and risks were reviewed before starting work.',
        'Sensitive receptors (waterways, drains, nearby community, protected zones) are identified and marked.',
        'Waste segregation is correctly applied at source (general, recyclable, hazardous).',
        'Waste bins/containers are labeled, covered, and not overflowing.',
        'Hazardous waste storage is bunded, secure, and protected from rain/wind.',
        'Chemical containers are clearly labeled and stored by compatibility requirements.',
        'Current SDS is available and accessible for all chemicals in use.',
        'Spill kits are present, stocked, and accessible at risk points.',
        'Fuel, oil, and chemical transfer points are checked for leaks before and after use.',
        'Secondary containment (bunds/drip trays) is intact and free from defects.',
        'No visible hydrocarbon or chemical stains indicate uncontrolled releases.',
        'Drain protection controls are in place for high-risk activities.',
        'No contaminated runoff is leaving the work area.',
        'Dust suppression measures are active and effective where needed.',
        'Air emissions/smoke from plant and generators are within acceptable limits.',
        'Noise controls are applied where environmental or health impacts are possible.',
        'Idle time for vehicles/equipment is minimized to reduce emissions.',
        'Housekeeping standards prevent litter, debris spread, and contamination.',
        'Topsoil/erosion/sediment controls are in place where ground disturbance occurs.',
        'Environmental signage and exclusion markings are visible and legible.',
        'Personnel can explain spill/release immediate response steps.',
        'Environmental incidents/near misses are reported and escalated per procedure.',
        'Previous environmental actions are closed out and verified with evidence.',
    ],
}
