# Generated by Django 5.2.1 on 2026-04-22 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ohs", "0010_capaaction_medicalprofile_medicalassessment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="flra",
            name="additional_controls_added",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="flra",
            name="crew",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="flra",
            name="dynamic_changes_noticed",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="flra",
            name="energy_isolation_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="flra",
            name="escalation_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="flra",
            name="shift",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="flra",
            name="simultaneous_operations",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="flra",
            name="stop_work_authority_used",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="flra",
            name="supervisor_signature",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="flra",
            name="weather_conditions",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="flra",
            name="worker_signatures",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="fra",
            name="acceptable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="fra",
            name="additional_controls",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="fra",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_fras",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fra",
            name="existing_controls",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="fra",
            name="hazard_category",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="fra",
            name="initial_risk_score",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fra",
            name="likelihood",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fra",
            name="persons_at_risk",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="fra",
            name="residual_likelihood",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fra",
            name="residual_risk_score",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fra",
            name="residual_severity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fra",
            name="review_frequency",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="fra",
            name="severity_score",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="action_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incident_actions_owned",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="affected_person_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="incident",
            name="body_part_affected",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="incident",
            name="closeout_verification",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="contributing_factors",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="corrective_actions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="crew",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="incident",
            name="department",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="incident",
            name="employment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("employee", "Employee"),
                    ("contractor", "Contractor"),
                    ("visitor", "Visitor"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="event_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="immediate_action_taken",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="incident_category",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="incident",
            name="injury_type",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="incident",
            name="investigation_completion_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="investigation_lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incident_investigations_led",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="lessons_learned",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="lost_time_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="incident",
            name="regulator_notification_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="reportable_to_regulator",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incident",
            name="root_cause",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="treatment_level",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("first_aid", "First Aid"),
                    ("medical_treatment", "Medical Treatment"),
                    ("hospitalization", "Hospitalization"),
                ],
                default="none",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="witnesses",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="jsa",
            name="additional_controls_required",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="jsa",
            name="pre_job_briefing_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jsa",
            name="required_competency",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="jsa",
            name="required_permit",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="jsa",
            name="required_ppe",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="jsa",
            name="responsible_person_per_control",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="jsa",
            name="revision_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="jsa",
            name="supervisor_approval",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_jsas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="jsa",
            name="tools_equipment_used",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="jsa",
            name="trigger_for_review",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="jsa",
            name="valid_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jsa",
            name="valid_to",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model_name", models.CharField(max_length=120)),
                ("object_id", models.CharField(max_length=50)),
                ("object_repr", models.CharField(max_length=255)),
                ("change_summary", models.TextField(blank=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="ohs.siteproject",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="ohs.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
