# Generated by Django 5.2.1 on 2026-04-22 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ohs", "0011_flra_additional_controls_added_flra_crew_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="KPIDailySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_date", models.DateField()),
                ("incident_count", models.PositiveIntegerField(default=0)),
                ("open_capa_count", models.PositiveIntegerField(default=0)),
                ("overdue_capa_count", models.PositiveIntegerField(default=0)),
                ("observation_count", models.PositiveIntegerField(default=0)),
                ("checklist_count", models.PositiveIntegerField(default=0)),
                ("training_completed_count", models.PositiveIntegerField(default=0)),
                ("training_total_count", models.PositiveIntegerField(default=0)),
                ("medical_due_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kpi_snapshots",
                        to="ohs.siteproject",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_snapshots",
                        to="ohs.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("-snapshot_date",),
                "unique_together": {("tenant", "site", "snapshot_date")},
            },
        ),
    ]
