# Generated by Django 5.2.1 on 2026-04-22 10:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ohs", "0012_kpidailysnapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="PTOChemicalHazardousSubstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(default="0623", editable=False, max_length=20),
                ),
                (
                    "version",
                    models.CharField(default="00", editable=False, max_length=10),
                ),
                (
                    "authored_by",
                    models.CharField(
                        default="E Hinamanjolo", editable=False, max_length=120
                    ),
                ),
                (
                    "approved_by",
                    models.CharField(default="T Zulu", editable=False, max_length=120),
                ),
                (
                    "form_issue_date",
                    models.DateField(
                        default=datetime.date(2022, 2, 15), editable=False
                    ),
                ),
                ("observer_name", models.CharField(max_length=255)),
                ("observer_employee_id", models.CharField(blank=True, max_length=50)),
                ("observer_job_title", models.CharField(blank=True, max_length=255)),
                ("observer_department", models.CharField(blank=True, max_length=255)),
                ("observer_date", models.DateField(blank=True, null=True)),
                ("observer_signature", models.CharField(blank=True, max_length=255)),
                ("employee_name", models.CharField(max_length=255)),
                ("employee_id", models.CharField(blank=True, max_length=50)),
                ("employee_job_title", models.CharField(blank=True, max_length=255)),
                ("employee_department", models.CharField(blank=True, max_length=255)),
                ("employee_observed_at", models.DateTimeField(blank=True, null=True)),
                ("employee_signature", models.CharField(blank=True, max_length=255)),
                (
                    "shift_mining",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("morning", "Morning"),
                            ("afternoon", "Afternoon"),
                            ("night", "Night"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "shift_other",
                    models.CharField(
                        blank=True,
                        choices=[("day", "Day"), ("night", "Night")],
                        max_length=20,
                    ),
                ),
                (
                    "crew_mining",
                    models.CharField(
                        blank=True,
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=10,
                    ),
                ),
                (
                    "crew_other",
                    models.CharField(
                        blank=True,
                        choices=[("1", "1"), ("2", "2"), ("3", "3"), ("N/A", "N/A")],
                        max_length=10,
                    ),
                ),
                (
                    "reason_for_observation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("incident_follow_up", "Incident follow up"),
                            ("training_follow_up", "Training follow up"),
                            ("task_infrequent", "Task infrequently performed"),
                            ("critical_task_audit", "Critical task audit"),
                            ("periodic_pto", "Periodic PTO"),
                            ("new_employee", "New Employee"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "notification_of_pto",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("in_advance", "Told in Advance"),
                            ("not_in_advance", "Not Told in Advance"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "competency_result",
                    models.CharField(
                        blank=True,
                        choices=[("C", "Competent"), ("NYC", "Not Yet Competent")],
                        max_length=3,
                    ),
                ),
                ("forwarded_to_hr", models.BooleanField(blank=True, null=True)),
                (
                    "follow_up_pto_recommended",
                    models.BooleanField(blank=True, null=True),
                ),
                ("action_1", models.CharField(blank=True, max_length=255)),
                ("action_1_responsible", models.CharField(blank=True, max_length=255)),
                ("action_1_by_when", models.DateField(blank=True, null=True)),
                ("action_2", models.CharField(blank=True, max_length=255)),
                ("action_2_responsible", models.CharField(blank=True, max_length=255)),
                ("action_2_by_when", models.DateField(blank=True, null=True)),
                ("action_3", models.CharField(blank=True, max_length=255)),
                ("action_3_responsible", models.CharField(blank=True, max_length=255)),
                ("action_3_by_when", models.DateField(blank=True, null=True)),
                (
                    "employee_superintendent_name",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "employee_superintendent_signature",
                    models.CharField(blank=True, max_length=255),
                ),
                ("step_01_compliant", models.BooleanField(blank=True, null=True)),
                ("step_01_comments", models.TextField(blank=True)),
                ("step_02_compliant", models.BooleanField(blank=True, null=True)),
                ("step_02_comments", models.TextField(blank=True)),
                ("step_03_compliant", models.BooleanField(blank=True, null=True)),
                ("step_03_comments", models.TextField(blank=True)),
                ("step_04_compliant", models.BooleanField(blank=True, null=True)),
                ("step_04_comments", models.TextField(blank=True)),
                ("step_05_compliant", models.BooleanField(blank=True, null=True)),
                ("step_05_comments", models.TextField(blank=True)),
                ("step_06_compliant", models.BooleanField(blank=True, null=True)),
                ("step_06_comments", models.TextField(blank=True)),
                ("step_07_compliant", models.BooleanField(blank=True, null=True)),
                ("step_07_comments", models.TextField(blank=True)),
                ("step_08_compliant", models.BooleanField(blank=True, null=True)),
                ("step_08_comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pto_chemical_hazardous_substances",
                        to="ohs.siteproject",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pto_chemical_hazardous_substances",
                        to="ohs.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
