# Generated by Django 5.2.1 on 2026-04-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ohs", "0013_ptochemicalhazardoussubstance"),
    ]

    operations = [
        migrations.AddField(
            model_name="ptochemicalhazardoussubstance",
            name="pto_type",
            field=models.CharField(
                choices=[
                    (
                        "chemicals_hazardous_substances",
                        "Chemicals & Hazardous Substances PTO",
                    ),
                    ("work_at_heights", "Work at Heights PTO"),
                    ("energy_isolation", "Energy Isolation PTO"),
                    (
                        "equipment_safeguards_protective_devices",
                        "Equipment Safeguards & Protective Devices PTO",
                    ),
                    ("identify_control_hazards", "Identify and Control Hazards PTO"),
                    (
                        "mobile_equipment_light_vehicles",
                        "Mobile Equipment & Light Vehicles PTO",
                    ),
                    (
                        "competent_capable_controlled",
                        "Competent, Capable and Controlled PTO",
                    ),
                    ("safe_operation_forklifts", "Safe Operation for Forklifts PTO"),
                    ("other_pto", "Other PTO Form"),
                ],
                default="chemicals_hazardous_substances",
                max_length=60,
            ),
        ),
    ]
