# Generated by Django 5.2.1 on 2026-04-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ohs", "0014_ptochemicalhazardoussubstance_pto_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="ptochemicalhazardoussubstance",
            name="step_09_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ptochemicalhazardoussubstance",
            name="step_09_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ptochemicalhazardoussubstance",
            name="step_10_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ptochemicalhazardoussubstance",
            name="step_10_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ptochemicalhazardoussubstance",
            name="step_11_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ptochemicalhazardoussubstance",
            name="step_11_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ptochemicalhazardoussubstance",
            name="step_12_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ptochemicalhazardoussubstance",
            name="step_12_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ptochemicalhazardoussubstance",
            name="step_13_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ptochemicalhazardoussubstance",
            name="step_13_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ptochemicalhazardoussubstance",
            name="step_14_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ptochemicalhazardoussubstance",
            name="step_14_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ptochemicalhazardoussubstance",
            name="step_15_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ptochemicalhazardoussubstance",
            name="step_15_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ptochemicalhazardoussubstance",
            name="step_16_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ptochemicalhazardoussubstance",
            name="step_16_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ptochemicalhazardoussubstance",
            name="step_17_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ptochemicalhazardoussubstance",
            name="step_17_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ptochemicalhazardoussubstance",
            name="step_18_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ptochemicalhazardoussubstance",
            name="step_18_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ptochemicalhazardoussubstance",
            name="step_19_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ptochemicalhazardoussubstance",
            name="step_19_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ptochemicalhazardoussubstance",
            name="step_20_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ptochemicalhazardoussubstance",
            name="step_20_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ptochemicalhazardoussubstance",
            name="step_21_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ptochemicalhazardoussubstance",
            name="step_21_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ptochemicalhazardoussubstance",
            name="step_22_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ptochemicalhazardoussubstance",
            name="step_22_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ptochemicalhazardoussubstance",
            name="step_23_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ptochemicalhazardoussubstance",
            name="step_23_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
