# Generated by Django 5.2.1 on 2026-04-22 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ohs", "0015_ptochemicalhazardoussubstance_step_09_comments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ptochemicalhazardoussubstance",
            name="pto_type",
            field=models.CharField(
                choices=[
                    (
                        "chemicals_hazardous_substances",
                        "Chemicals & Hazardous Substances PTO",
                    ),
                    ("work_at_heights", "Work at Heights PTO"),
                    ("energy_isolation", "Energy Isolation PTO"),
                    (
                        "equipment_safeguards_protective_devices",
                        "Equipment Safeguards & Protective Devices PTO",
                    ),
                    ("identify_control_hazards", "Identify and Control Hazards PTO"),
                    (
                        "mobile_equipment_light_vehicles",
                        "Mobile Equipment & Light Vehicles PTO",
                    ),
                    (
                        "competent_capable_controlled",
                        "Competent, Capable and Controlled PTO",
                    ),
                    ("safe_operation_forklifts", "Safe Operation for Forklifts PTO"),
                ],
                default="chemicals_hazardous_substances",
                max_length=60,
            ),
        ),
        migrations.CreateModel(
            name="CCVCriticalControlVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ccv_type",
                    models.CharField(
                        choices=[("mobile_equipment", "Mobile Equipment CCV")],
                        default="mobile_equipment",
                        max_length=60,
                    ),
                ),
                ("assessor_name", models.CharField(max_length=255)),
                ("assessment_datetime", models.DateTimeField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("department", models.CharField(blank=True, max_length=255)),
                ("section", models.CharField(blank=True, max_length=255)),
                ("step_01_compliant", models.BooleanField(blank=True, null=True)),
                ("step_01_comments", models.TextField(blank=True)),
                ("step_02_compliant", models.BooleanField(blank=True, null=True)),
                ("step_02_comments", models.TextField(blank=True)),
                ("step_03_compliant", models.BooleanField(blank=True, null=True)),
                ("step_03_comments", models.TextField(blank=True)),
                ("step_04_compliant", models.BooleanField(blank=True, null=True)),
                ("step_04_comments", models.TextField(blank=True)),
                ("step_05_compliant", models.BooleanField(blank=True, null=True)),
                ("step_05_comments", models.TextField(blank=True)),
                ("step_06_compliant", models.BooleanField(blank=True, null=True)),
                ("step_06_comments", models.TextField(blank=True)),
                ("step_07_compliant", models.BooleanField(blank=True, null=True)),
                ("step_07_comments", models.TextField(blank=True)),
                ("step_08_compliant", models.BooleanField(blank=True, null=True)),
                ("step_08_comments", models.TextField(blank=True)),
                ("step_09_compliant", models.BooleanField(blank=True, null=True)),
                ("step_09_comments", models.TextField(blank=True)),
                ("step_10_compliant", models.BooleanField(blank=True, null=True)),
                ("step_10_comments", models.TextField(blank=True)),
                ("step_11_compliant", models.BooleanField(blank=True, null=True)),
                ("step_11_comments", models.TextField(blank=True)),
                ("step_12_compliant", models.BooleanField(blank=True, null=True)),
                ("step_12_comments", models.TextField(blank=True)),
                ("step_13_compliant", models.BooleanField(blank=True, null=True)),
                ("step_13_comments", models.TextField(blank=True)),
                ("step_14_compliant", models.BooleanField(blank=True, null=True)),
                ("step_14_comments", models.TextField(blank=True)),
                ("step_15_compliant", models.BooleanField(blank=True, null=True)),
                ("step_15_comments", models.TextField(blank=True)),
                ("step_16_compliant", models.BooleanField(blank=True, null=True)),
                ("step_16_comments", models.TextField(blank=True)),
                ("step_17_compliant", models.BooleanField(blank=True, null=True)),
                ("step_17_comments", models.TextField(blank=True)),
                ("step_18_compliant", models.BooleanField(blank=True, null=True)),
                ("step_18_comments", models.TextField(blank=True)),
                ("step_19_compliant", models.BooleanField(blank=True, null=True)),
                ("step_19_comments", models.TextField(blank=True)),
                ("step_20_compliant", models.BooleanField(blank=True, null=True)),
                ("step_20_comments", models.TextField(blank=True)),
                ("step_21_compliant", models.BooleanField(blank=True, null=True)),
                ("step_21_comments", models.TextField(blank=True)),
                ("step_22_compliant", models.BooleanField(blank=True, null=True)),
                ("step_22_comments", models.TextField(blank=True)),
                ("step_23_compliant", models.BooleanField(blank=True, null=True)),
                ("step_23_comments", models.TextField(blank=True)),
                ("action_1", models.CharField(blank=True, max_length=255)),
                ("action_1_responsible", models.CharField(blank=True, max_length=255)),
                ("action_1_due_date", models.DateField(blank=True, null=True)),
                ("action_2", models.CharField(blank=True, max_length=255)),
                ("action_2_responsible", models.CharField(blank=True, max_length=255)),
                ("action_2_due_date", models.DateField(blank=True, null=True)),
                ("action_3", models.CharField(blank=True, max_length=255)),
                ("action_3_responsible", models.CharField(blank=True, max_length=255)),
                ("action_3_due_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ccv_critical_control_verifications",
                        to="ohs.siteproject",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ccv_critical_control_verifications",
                        to="ohs.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
