# Generated by Django 5.2.1 on 2026-04-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ohs", "0016_alter_ptochemicalhazardoussubstance_pto_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ccvcriticalcontrolverification",
            name="ccv_type",
            field=models.CharField(
                choices=[
                    ("mobile_equipment", "Mobile Equipment CCV"),
                    ("rotating_equipment", "Rotating Equipment CCV"),
                ],
                default="mobile_equipment",
                max_length=60,
            ),
        ),
    ]
