# Generated by Django 5.2.1 on 2026-04-22 15:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ohs", "0024_jsa_fm0464_and_steps"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="safetychecklist",
            options={"ordering": ("-date_completed",)},
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="actions_required",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="checklist_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="equipment_id",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="findings",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="inspection_area",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="next_due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="operational_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("good", "Good"),
                    ("needs_attention", "Needs Attention"),
                    ("out_of_service", "Out Of Service"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="verified_by",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="safetychecklist",
            name="checklist_type",
            field=models.CharField(
                choices=[
                    ("Daily", "Daily"),
                    ("Weekly", "Weekly"),
                    ("Monthly", "Monthly"),
                    ("LV Vehicle", "LV Vehicle Checklist"),
                    ("Drilling Machine Surface", "Drilling Machine Surface Checklist"),
                    ("Environmental", "Environmental Checklist"),
                    ("Generator", "Generator Checklist"),
                    ("Other Operational", "Other Operational Checklist"),
                ],
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="ToolboxTalk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("talk_date", models.DateField(default=datetime.date.today)),
                ("facilitator_name", models.CharField(blank=True, max_length=255)),
                ("department", models.CharField(blank=True, max_length=255)),
                ("work_group", models.CharField(blank=True, max_length=255)),
                ("topic_details", models.TextField(blank=True)),
                ("hazards_discussed", models.TextField(blank=True)),
                ("controls_agreed", models.TextField(blank=True)),
                ("attendance_count", models.PositiveIntegerField(default=0)),
                ("attendees", models.TextField(blank=True)),
                ("action_items", models.TextField(blank=True)),
                ("follow_up_required", models.BooleanField(default=False)),
                ("follow_up_owner", models.CharField(blank=True, max_length=255)),
                ("follow_up_due_date", models.DateField(blank=True, null=True)),
                (
                    "toolbox_file",
                    models.FileField(
                        blank=True, null=True, upload_to="toolbox_talks/files/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conducted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="toolbox_talks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="toolbox_talks",
                        to="ohs.siteproject",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="toolbox_talks",
                        to="ohs.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("-talk_date", "-id"),
            },
        ),
    ]
