# Generated by Django 5.2.1 on 2026-04-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ohs", "0026_analyticswarehousedaily"),
    ]

    operations = [
        migrations.AddField(
            model_name="flra",
            name="selected_employees",
            field=models.ManyToManyField(
                blank=True, related_name="flra_entries", to="ohs.employee"
            ),
        ),
    ]
