# Generated by Django 4.2.8 on 2026-04-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ohs", "0027_flra_selected_employees"),
    ]

    operations = [
        migrations.AddField(
            model_name="safetychecklist",
            name="deviation_action_taken",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="deviation_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="deviation_problem",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="deviation_reported_to",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="document_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="document_status",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="drill_rig_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="effective_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="lighting_tower_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="maintenance_supervisor_signature",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="operator_signature",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="revision_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="serial_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="site_supervisor_signature",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_01_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_01_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_02_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_02_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_03_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_03_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_04_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_04_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_05_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_05_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_06_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_06_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_07_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_07_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_08_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_08_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_09_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_09_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_10_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_10_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_11_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_11_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_12_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_12_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_13_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_13_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_14_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_14_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_15_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_15_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_16_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_16_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_17_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_17_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_18_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_18_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_19_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_19_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_20_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_20_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_21_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_21_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_22_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_22_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_23_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_23_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_24_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_24_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_25_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_25_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_26_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_26_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_27_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_27_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_28_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_28_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_29_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_29_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="safetychecklist",
            name="checklist_type",
            field=models.CharField(
                choices=[
                    ("Daily", "Daily"),
                    ("Weekly", "Weekly"),
                    ("Monthly", "Monthly"),
                    ("LV Vehicle", "LV Vehicle Checklist"),
                    ("Lighting Tower", "Lighting Tower Inspection Checklist"),
                    ("Drilling Machine Surface", "Drilling Machine Surface Checklist"),
                    ("Environmental", "Environmental Checklist"),
                    ("Generator", "Generator Checklist"),
                    ("Other Operational", "Other Operational Checklist"),
                ],
                max_length=40,
            ),
        ),
    ]
