# Generated by Django 4.2.8 on 2026-04-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ohs", "0028_safetychecklist_deviation_action_taken_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="safetychecklist",
            name="area_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="company_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="operator_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_30_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_30_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_31_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_31_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_32_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_32_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_33_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_33_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_34_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_34_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_35_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_35_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_36_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_36_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_37_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_37_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_38_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_38_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_39_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_39_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_40_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_40_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_41_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_41_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_42_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_42_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_43_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_43_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_44_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_44_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_45_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_45_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_46_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_46_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_47_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="step_47_compliant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetychecklist",
            name="supervisor_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="safetychecklist",
            name="checklist_type",
            field=models.CharField(
                choices=[
                    ("Daily", "Daily"),
                    ("Weekly", "Weekly"),
                    ("Monthly", "Monthly"),
                    ("LV Vehicle", "LV Vehicle Checklist"),
                    ("Lighting Tower", "Lighting Tower Inspection Checklist"),
                    ("Drill Rig", "Drill Rig Inspection Checklist"),
                    ("Drilling Machine Surface", "Drilling Machine Surface Checklist"),
                    ("Environmental", "Environmental Checklist"),
                    ("Generator", "Generator Checklist"),
                    ("Other Operational", "Other Operational Checklist"),
                ],
                max_length=40,
            ),
        ),
    ]
