# Generated by Django 4.2.8 on 2026-04-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ohs", "0030_alter_safetychecklist_checklist_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteproject",
            name="site_attachment",
            field=models.FileField(blank=True, null=True, upload_to="site_projects/"),
        ),
    ]
