# Generated by Django 5.2.1 on 2026-05-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ohs", "0034_tenantpreset"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="expert_traits",
            field=models.TextField(
                blank=True, help_text="Comma-separated list of expertise areas"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="scope",
            field=models.CharField(
                choices=[
                    ("local", "Local"),
                    ("regional", "Regional"),
                    ("national", "National"),
                    ("expatriate", "Expatriate"),
                ],
                default="local",
                max_length=20,
            ),
        ),
    ]
