# Generated by Django 5.2.1 on 2026-05-20 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ohs", "0036_attendancerecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "man_hours_target",
                    models.PositiveIntegerField(
                        default=1000, help_text="Monthly man-hours target"
                    ),
                ),
                (
                    "incident_target",
                    models.PositiveIntegerField(
                        default=0, help_text="Target incidents (0 = zero tolerance)"
                    ),
                ),
                (
                    "jsa_target",
                    models.PositiveIntegerField(
                        default=10, help_text="Monthly JSAs target"
                    ),
                ),
                (
                    "fra_target",
                    models.PositiveIntegerField(
                        default=5, help_text="Monthly FRAs target"
                    ),
                ),
                (
                    "flra_target",
                    models.PositiveIntegerField(
                        default=100, help_text="Monthly FLRAs target"
                    ),
                ),
                (
                    "ccv_target",
                    models.PositiveIntegerField(
                        default=20, help_text="Monthly CCVs target"
                    ),
                ),
                (
                    "safety_incidents_severity_target",
                    models.CharField(
                        choices=[
                            ("none", "Zero High Severity"),
                            ("low", "Only Low Severity"),
                            ("any", "All Types"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site_project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preset",
                        to="ohs.siteproject",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_presets",
                        to="ohs.tenant",
                    ),
                ),
            ],
            options={
                "unique_together": {("site_project", "tenant")},
            },
        ),
    ]
