# Generated by Django 5.2.1 on 2026-05-22 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ohs", "0037_projectpreset"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlySiteHealthReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_month",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "January"),
                            (2, "February"),
                            (3, "March"),
                            (4, "April"),
                            (5, "May"),
                            (6, "June"),
                            (7, "July"),
                            (8, "August"),
                            (9, "September"),
                            (10, "October"),
                            (11, "November"),
                            (12, "December"),
                        ],
                        default=1,
                    ),
                ),
                ("report_year", models.PositiveIntegerField(default=2026)),
                ("safety_summary", models.TextField(blank=True)),
                ("incident_count", models.PositiveIntegerField(default=0)),
                ("near_miss_count", models.PositiveIntegerField(default=0)),
                ("observation_count", models.PositiveIntegerField(default=0)),
                ("inspection_count", models.PositiveIntegerField(default=0)),
                (
                    "training_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "man_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="monthly_health_reports_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_site_health_reports",
                        to="ohs.siteproject",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_site_health_reports",
                        to="ohs.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("-report_year", "-report_month", "-site_project"),
                "unique_together": {
                    ("tenant", "site_project", "report_month", "report_year")
                },
            },
        ),
    ]
