# Generated by Django 5.2.1 on 2026-06-10 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ohs", "0038_monthlysitehealthreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="safetychecklist",
            name="date_completed",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
