# Generated by Django 5.2.1 on 2026-06-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ohs", "0039_alter_safetychecklist_date_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantpreset",
            name="company_logo",
            field=models.ImageField(blank=True, null=True, upload_to="tenant_logos/"),
        ),
    ]
