# Generated by Django 5.2.1 on 2026-06-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ohs", "0040_add_company_logo_to_tenantpreset"),
    ]

    operations = [
        migrations.AddField(
            model_name="toolboxtalk",
            name="attendee_employees",
            field=models.ManyToManyField(
                blank=True, related_name="toolbox_attendance", to="ohs.employee"
            ),
        ),
        migrations.AlterField(
            model_name="toolboxtalk",
            name="attendees",
            field=models.TextField(
                blank=True,
                help_text="Additional attendees not in the employee register (contractors, visitors, etc.)",
            ),
        ),
    ]
