# Generated by Django 5.2.1 on 2026-06-11 09:04

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ohs", "0041_add_attendee_employees_to_toolboxtalk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EnergyWaterConsumption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reading_date", models.DateField(default=datetime.date.today)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("electricity_kwh", "Electricity (kWh)"),
                            ("diesel_litres", "Diesel (Litres)"),
                            ("water_m3", "Water (m³)"),
                            ("lpg_kg", "LPG (kg)"),
                            ("petrol_litres", "Petrol (Litres)"),
                            ("natural_gas_m3", "Natural Gas (m³)"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("meter_reference", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="energy_readings_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="energy_consumption",
                        to="ohs.siteproject",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="energy_consumption",
                        to="ohs.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("-reading_date",),
            },
        ),
        migrations.CreateModel(
            name="EnvironmentalAspect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity", models.CharField(max_length=255)),
                (
                    "aspect",
                    models.CharField(
                        help_text="The environmental aspect (e.g. fuel combustion)",
                        max_length=255,
                    ),
                ),
                (
                    "potential_impact",
                    models.CharField(
                        help_text="The potential environmental impact", max_length=255
                    ),
                ),
                (
                    "impact_type",
                    models.CharField(
                        choices=[
                            ("air", "Air Quality / Emissions"),
                            ("water", "Water Quality / Discharge"),
                            ("land", "Land Contamination"),
                            ("waste", "Waste Generation"),
                            ("energy", "Energy Consumption"),
                            ("noise", "Noise Pollution"),
                            ("biodiversity", "Biodiversity Impact"),
                            ("community", "Community Impact"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "operating_condition",
                    models.CharField(
                        choices=[
                            ("normal", "Normal Operations"),
                            ("abnormal", "Abnormal Operations"),
                            ("emergency", "Emergency Conditions"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "significance",
                    models.CharField(
                        choices=[
                            ("significant", "Significant"),
                            ("moderate", "Moderate"),
                            ("minor", "Minor"),
                        ],
                        default="moderate",
                        max_length=20,
                    ),
                ),
                ("control_measure", models.TextField(blank=True)),
                ("legal_requirement", models.TextField(blank=True)),
                ("monitoring_required", models.BooleanField(default=False)),
                ("review_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="environmental_aspects",
                        to="ohs.siteproject",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="environmental_aspects",
                        to="ohs.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="EnvironmentalObjective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("target_description", models.TextField()),
                ("indicator", models.CharField(blank=True, max_length=255)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("on_track", "On Track"),
                            ("at_risk", "At Risk"),
                            ("behind", "Behind Schedule"),
                            ("achieved", "Achieved"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="on_track",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "responsible_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="env_objectives_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="env_objectives",
                        to="ohs.siteproject",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="env_objectives",
                        to="ohs.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="SpillReleaseIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("incident_date", models.DateTimeField()),
                (
                    "substance",
                    models.CharField(
                        choices=[
                            ("fuel_oil", "Fuel / Oil"),
                            ("chemical", "Chemical / Reagent"),
                            ("sewage", "Sewage / Wastewater"),
                            ("stormwater", "Contaminated Stormwater Runoff"),
                            ("dust", "Fugitive Dust"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quantity_litres",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("minor", "Minor — Contained on site, no off-site impact"),
                            ("moderate", "Moderate — Potential off-site impact"),
                            (
                                "major",
                                "Major — Off-site impact, regulatory notification required",
                            ),
                        ],
                        max_length=10,
                    ),
                ),
                ("location_description", models.TextField()),
                ("cause", models.TextField(blank=True)),
                ("immediate_action", models.TextField(blank=True)),
                (
                    "regulatory_notification_required",
                    models.BooleanField(default=False),
                ),
                ("regulatory_notification_sent", models.BooleanField(default=False)),
                ("cleanup_completed", models.BooleanField(default=False)),
                ("cleanup_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spills_reported",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="spill_incidents",
                        to="ohs.siteproject",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spill_incidents",
                        to="ohs.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("-incident_date",),
            },
        ),
        migrations.CreateModel(
            name="WasteManagementLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("log_date", models.DateField(default=datetime.date.today)),
                (
                    "waste_type",
                    models.CharField(
                        choices=[
                            ("general", "General Waste"),
                            ("hazardous", "Hazardous Waste"),
                            ("chemical", "Chemical Waste"),
                            ("medical", "Medical / Biological Waste"),
                            ("electronic", "E-Waste / Electronic"),
                            ("construction", "Construction / Demolition Debris"),
                            ("recyclable", "Recyclable Material"),
                            ("organic", "Organic / Food Waste"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "quantity_kg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "disposal_method",
                    models.CharField(
                        choices=[
                            ("landfill", "Landfill"),
                            ("recycling", "Recycling Facility"),
                            ("incineration", "Incineration"),
                            ("licensed_disposal", "Licensed Disposal Contractor"),
                            ("reuse", "Reuse / Repurpose"),
                            ("composting", "Composting"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("disposal_contractor", models.CharField(blank=True, max_length=255)),
                ("manifest_number", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waste_logs_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="waste_logs",
                        to="ohs.siteproject",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waste_logs",
                        to="ohs.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("-log_date",),
            },
        ),
    ]
